apiVersion: serving.knative.dev/v1alpha1
kind: Route
metadata:
  name: myfirstserverlessapp
  namespace: hackathon-pi-knative
spec:
  traffic:
  - revisionName: "v1Placeholder"
    percent: 100
    name: v1
  # - revisionName: "v2Placeholder"
  #   percent: 0
  #   name: v2
