apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: myfirstserverlessapp
  namespace: hackathon-pi-knative
spec:
  runLatest:
    configuration:
      revisionTemplate:
        metadata:
          annotations:
            autoscaling.knative.dev/target: "1"
            autoscaling.knative.dev/maxScale: "10"
        spec:
          container:
            image: leggsy/myfirstserverlessapp:latest
