apiVersion: serving.knative.dev/v1alpha1
kind: Configuration
metadata:
  name: myfirstserverlessapp
  namespace: hackathon-pi-knative
spec:
  revisionTemplate:
    metadata:
      labels:
        knative.dev/type: container
    spec:
      container:
        image: leggsy/myfirstserverlessapp:v1
        env:
          - name: COLOUR
            value: "blue"